/**
 * Provisions an isolated Postgres schema for integration tests.
 *
 * Why a derived schema file rather than a second database:
 * every model in prisma/schema.prisma is pinned to the "athlasx" schema via
 * @@schema, so a connection-string tweak cannot redirect writes. We instead
 * generate a parallel schema whose models live in "athlasx_test", emit a
 * separate Prisma Client for it, and push the tables there.
 *
 * The live "athlasx" schema and the legacy "public" schema are never touched.
 *
 *   node scripts/setup-test-db.mjs          # create / update
 *   node scripts/setup-test-db.mjs --drop   # tear down
 */
import fs from 'node:fs'
import path from 'node:path'
import { execFileSync } from 'node:child_process'

const ROOT = process.cwd()
const SRC_SCHEMA = path.join(ROOT, 'prisma', 'schema.prisma')
const TEST_SCHEMA = path.join(ROOT, 'prisma', 'schema.test.prisma')
const TEST_CLIENT_OUT = path.join(ROOT, 'node_modules', '.prisma-test', 'client')
export const TEST_SCHEMA_NAME = 'athlasx_test'

function loadEnvLocal() {
  const p = path.join(ROOT, '.env.local')
  if (!fs.existsSync(p)) return
  for (const line of fs.readFileSync(p, 'utf8').split(/\r?\n/)) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)$/)
    if (m && process.env[m[1]] === undefined) {
      process.env[m[1]] = m[2].trim().replace(/^["']|["']$/g, '')
    }
  }
}

function writeDerivedSchema() {
  let s = fs.readFileSync(SRC_SCHEMA, 'utf8')

  // Re-point every model and the datasource at the test schema.
  s = s.replaceAll('@@schema("athlasx")', `@@schema("${TEST_SCHEMA_NAME}")`)
  s = s.replace(/schemas\s*=\s*\[\s*"athlasx"\s*\]/, `schemas   = ["${TEST_SCHEMA_NAME}"]`)

  // Emit the client somewhere that cannot shadow the app's own client.
  s = s.replace(
    /generator client \{([\s\S]*?)\}/,
    (_m, body) => `generator client {${body.replace(/\s*$/, '')}\n  output   = "${TEST_CLIENT_OUT.replace(/\\/g, '/')}"\n}`,
  )

  const banner =
    '// GENERATED by scripts/setup-test-db.mjs — do not edit, do not commit.\n' +
    `// Mirror of prisma/schema.prisma pinned to the "${TEST_SCHEMA_NAME}" schema.\n\n`
  fs.writeFileSync(TEST_SCHEMA, banner + s, 'utf8')

  const pinned = (s.match(/@@schema\("athlasx_test"\)/g) || []).length
  if (!pinned) throw new Error('derived schema has no athlasx_test models — refusing to continue')
  if (s.includes('@@schema("athlasx")')) throw new Error('derived schema still references athlasx — refusing')
  return pinned
}

function run(args) {
  execFileSync('npx', ['prisma', ...args], {
    stdio: 'inherit',
    env: process.env,
    shell: process.platform === 'win32',
  })
}

async function dropSchema() {
  const { PrismaClient } = await import('@prisma/client')
  const db = new PrismaClient()
  try {
    await db.$executeRawUnsafe(`DROP SCHEMA IF EXISTS ${TEST_SCHEMA_NAME} CASCADE`)
    console.log(`dropped schema ${TEST_SCHEMA_NAME}`)
  } finally {
    await db.$disconnect()
  }
}

async function main() {
  loadEnvLocal()
  if (!process.env.DATABASE_URL) throw new Error('DATABASE_URL is not set (checked .env.local)')

  if (process.argv.includes('--drop')) {
    await dropSchema()
    fs.rmSync(TEST_SCHEMA, { force: true })
    return
  }

  const models = writeDerivedSchema()
  console.log(`derived schema written: ${models} models pinned to ${TEST_SCHEMA_NAME}`)

  // Relative path: the repo lives under a directory containing a space, and
  // execFileSync with shell:true on Windows does not quote arguments.
  const REL = 'prisma/schema.test.prisma'
  run(['generate', '--schema', REL])
  run(['db', 'push', '--schema', REL, '--skip-generate', '--accept-data-loss'])

  console.log(`\ntest schema "${TEST_SCHEMA_NAME}" is ready`)
  console.log('the live "athlasx" and legacy "public" schemas were not touched')
}

main().catch(e => {
  console.error('\nsetup-test-db failed:', e.message)
  process.exit(1)
})
