/**
 * Integration-test database harness.
 *
 * Routes under test import `{ db } from '@/lib/db'`, which is bound to the
 * live "athlasx" schema. Each integration suite calls `mockDb()` FIRST so
 * that import resolves to a client bound to "athlasx_test" instead. The live
 * schema is never opened by a test.
 *
 * Provision the schema once before running:  npm run test:setup-db
 */
// Generated by scripts/setup-test-db.mjs — pinned to the athlasx_test schema.
// eslint-disable-next-line @typescript-eslint/no-var-requires
import { PrismaClient } from '../../node_modules/.prisma-test/client/index.js'
import { hashPassword } from '../../src/lib/password'

export const testDb = new PrismaClient({
  datasourceUrl: process.env.DATABASE_DIRECT_URL || process.env.DATABASE_URL,
})
const DEV_PASSWORD = 'athlasx-dev-password'

/**
 * Each integration suite must hoist this at its own top level:
 *
 *   vi.mock('@/lib/db', async () => ({
 *     db: (await import('../helpers/test-db')).testDb,
 *   }))
 *
 * vi.mock is hoisted per-file, so it cannot be wrapped in a helper function.
 */

/** Neon autosuspends; the first connection after idle can time out once. */
export async function withRetry<T>(fn: () => Promise<T>, attempts = 4): Promise<T> {
  let last: unknown
  for (let i = 0; i < attempts; i++) {
    try {
      return await fn()
    } catch (e) {
      last = e
      await new Promise(r => setTimeout(r, 2000 * (i + 1)))
    }
  }
  throw last
}

/** Guard: refuse to run if the harness is somehow pointed at live data. */
export async function assertIsTestSchema() {
  const rows = await withRetry(() =>
    testDb.$queryRawUnsafe<{ current_schema: string }[]>(
      "SELECT current_setting('search_path') AS current_schema",
    ),
  )
  const live = await withRetry(() =>
    testDb.$queryRawUnsafe<{ n: number }[]>(
      "SELECT count(*)::int AS n FROM information_schema.tables WHERE table_schema='athlasx_test'",
    ),
  )
  if (live[0].n === 0) {
    throw new Error(
      'athlasx_test schema is empty or missing — run `node scripts/setup-test-db.mjs` first',
    )
  }
  return rows
}

/**
 * Delete every row, child tables first. Called between suites so each starts
 * from a known state without dropping and re-pushing the schema.
 */
export async function resetDb() {
  await withRetry(() =>
    testDb.$executeRawUnsafe(`
      TRUNCATE TABLE
        athlasx_test.identity_exceptions,
        athlasx_test.association_staff,
        athlasx_test.omission_rationales,
        athlasx_test.selections,
        athlasx_test.grades,
        athlasx_test.selection_sessions,
        athlasx_test.session_attendance,
        athlasx_test.training_sessions,
        athlasx_test.coach_advisory_notes,
        athlasx_test.squad_players,
        athlasx_test.squad_coaches,
        athlasx_test.squads,
        athlasx_test.dossiers,
        athlasx_test.registrations,
        athlasx_test.trial_venues,
        athlasx_test.trial_cycles,
        athlasx_test.trend_alerts,
        athlasx_test.player_weeks,
        athlasx_test.performances,
        athlasx_test.matches,
        athlasx_test.tournaments,
        athlasx_test.academy_match_candidates,
        athlasx_test.academies,
        athlasx_test.phone_otps,
        athlasx_test.player_claims,
        athlasx_test.ingest_jobs,
        athlasx_test.coach_profiles,
        athlasx_test.selector_profiles,
        athlasx_test.player_profiles,
        athlasx_test.users,
        athlasx_test.associations
      RESTART IDENTITY CASCADE
    `),
  )
}

export type Fixtures = Awaited<ReturnType<typeof seedFixtures>>

/**
 * A minimal but realistic slice of the domain:
 *   one association, one adult player, one minor player (unclaimed shadow
 *   profile), two selectors, a grading session, and a trial cycle.
 */
export async function seedFixtures() {
  const association = await testDb.association.create({
    data: { name: 'Test District CA', type: 'district', state: 'Uttar Pradesh' },
  })

  const adult = await testDb.playerProfile.create({
    data: {
      full_name: 'Adult Player',
      dob: new Date('2000-01-01'),
      district: 'Kanpur',
      state: 'Uttar Pradesh',
      playing_role: 'Batsman',
      claim_status: 'unclaimed',
      consent_status: 'not_required',
      profile_source: 'ingest',
      association_id: association.id,
    },
  })

  // Under 18 relative to today — the DPDP-sensitive case.
  const minorDob = new Date()
  minorDob.setFullYear(minorDob.getFullYear() - 15)
  const minor = await testDb.playerProfile.create({
    data: {
      full_name: 'Minor Player',
      dob: minorDob,
      district: 'Lucknow',
      state: 'Uttar Pradesh',
      playing_role: 'Bowler',
      claim_status: 'unclaimed',
      consent_status: 'pending',
      profile_source: 'ingest',
      association_id: association.id,
    },
  })

  const chair = await testDb.user.create({
    data: { email: 'chair@test.local', role: 'selection_panel', password_hash: await hashPassword(DEV_PASSWORD) },
  })
  const selectorB = await testDb.user.create({
    data: { email: 'selector-b@test.local', role: 'selection_panel', password_hash: await hashPassword(DEV_PASSWORD) },
  })
  const associationStaffUser = await testDb.user.create({
    data: { email: 'staff@test.local', role: 'association', password_hash: await hashPassword(DEV_PASSWORD) },
  })

  await testDb.selectorProfile.create({
    data: { user_id: chair.id, full_name: 'Test Chair', association_id: association.id },
  })
  await testDb.selectorProfile.create({
    data: { user_id: selectorB.id, full_name: 'Test Selector B', association_id: association.id },
  })

  // `chair` doubles as the generic "association-scoped staff caller" in
  // several existing integration tests (candidate-pool, tracking,
  // coach/squad — all called with role: 'association'), on top of being
  // the grading session's own chair. Association-scoped routes derive
  // access from real AssociationStaff membership (src/lib/
  // association-scope.ts), not from the role string on the session token,
  // so without a real membership row those calls would 403/see nothing —
  // this row is what makes `chair` a legitimate stand-in for both roles.
  await testDb.associationStaff.create({
    data: { association_id: association.id, user_id: chair.id },
  })
  await testDb.associationStaff.create({
    data: { association_id: association.id, user_id: associationStaffUser.id, is_lead: true },
  })

  const trialCycle = await testDb.trialCycle.create({
    data: {
      association_id: association.id,
      age_category: 'U19',
      dob_window_start: new Date('2007-09-01'),
      dob_window_end: new Date('2010-08-31'),
      fee_amount: 400,
      registration_opens: new Date(Date.now() - 7 * 864e5),
      registration_closes: new Date(Date.now() + 7 * 864e5),
      status: 'registration_open',
    },
  })

  const session = await testDb.selectionSession.create({
    data: {
      trial_cycle_id: trialCycle.id,
      association_id: association.id,
      chair_id: chair.id,
      squad_size_target: 20,
      status: 'grading',
    },
  })

  return { association, adult, minor, chair, selectorB, associationStaffUser, trialCycle, session }
}
